// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.repository;

import br.com.rogrs.repository.CustomerRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CustomerRepository_Roo_Jpa_Repository {
    
    declare @type: CustomerRepository: @Transactional(readOnly = true);
    
}
