// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model.dod;

import br.com.rogrs.model.Address;
import br.com.rogrs.model.Customer;
import br.com.rogrs.model.dod.AddressFactory;

privileged aspect AddressFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Address} with the given index.
     * 
     * @param index position of the Address
     * @return a new transient Address
     */
    public Address AddressFactory.create(int index) {
        Address obj = new Address();
        setCity(obj, index);
        setCustomer(obj, index);
        setStreet(obj, index);
        setStreetNumber(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void AddressFactory.setCity(Address obj, int index) {
        String city = "city_" + index;
        obj.setCity(city);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void AddressFactory.setCustomer(Address obj, int index) {
        Customer customer = null;
        obj.setCustomer(customer);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void AddressFactory.setStreet(Address obj, int index) {
        String street = "street_" + index;
        obj.setStreet(street);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void AddressFactory.setStreetNumber(Address obj, int index) {
        Integer streetNumber = new Integer(index);
        if (streetNumber < 1) {
            streetNumber = 1;
        }
        obj.setStreetNumber(streetNumber);
    }
    
}
