// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model.dod;

import br.com.rogrs.model.Category;
import br.com.rogrs.model.dod.CategoryFactory;

privileged aspect CategoryFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Category} with the given index.
     * 
     * @param index position of the Category
     * @return a new transient Category
     */
    public Category CategoryFactory.create(int index) {
        Category obj = new Category();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CategoryFactory.setDescription(Category obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CategoryFactory.setName(Category obj, int index) {
        String name = "name_" + index;
        if (name.length() > 30) {
            name = name.substring(0, 30);
        }
        obj.setName(name);
    }
    
}
