// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model.dod;

import br.com.rogrs.model.Address;
import br.com.rogrs.model.Customer;
import br.com.rogrs.model.dod.CustomerFactory;

privileged aspect CustomerFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Customer} with the given index.
     * 
     * @param index position of the Customer
     * @return a new transient Customer
     */
    public Customer CustomerFactory.create(int index) {
        Customer obj = new Customer();
        setAddress(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setAddress(Customer obj, int index) {
        Address address = null;
        obj.setAddress(address);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setFirstName(Customer obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerFactory.setLastName(Customer obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
}
