// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model.dod;

import br.com.rogrs.model.Customer;
import br.com.rogrs.model.CustomerOrder;
import br.com.rogrs.model.dod.CustomerOrderFactory;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

privileged aspect CustomerOrderFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link CustomerOrder} with the given index.
     * 
     * @param index position of the CustomerOrder
     * @return a new transient CustomerOrder
     */
    public CustomerOrder CustomerOrderFactory.create(int index) {
        CustomerOrder obj = new CustomerOrder();
        setCustomer(obj, index);
        setOrderDate(obj, index);
        setShipAddress(obj, index);
        setShippedDate(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setCustomer(CustomerOrder obj, int index) {
        Customer customer = null;
        obj.setCustomer(customer);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setOrderDate(CustomerOrder obj, int index) {
        Date orderDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), 
			Calendar.getInstance().get(Calendar.MONTH), 
			Calendar.getInstance().get(Calendar.DAY_OF_MONTH), 
			Calendar.getInstance().get(Calendar.HOUR_OF_DAY), 
			Calendar.getInstance().get(Calendar.MINUTE), 
			Calendar.getInstance().get(Calendar.SECOND) + 
			new Double(Math.random() * 1000).intValue()).getTime();
        obj.setOrderDate(orderDate);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShipAddress(CustomerOrder obj, int index) {
        String shipAddress = "shipAddress_" + index;
        obj.setShipAddress(shipAddress);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void CustomerOrderFactory.setShippedDate(CustomerOrder obj, int index) {
        Date shippedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), 
			Calendar.getInstance().get(Calendar.MONTH), 
			Calendar.getInstance().get(Calendar.DAY_OF_MONTH), 
			Calendar.getInstance().get(Calendar.HOUR_OF_DAY), 
			Calendar.getInstance().get(Calendar.MINUTE), 
			Calendar.getInstance().get(Calendar.SECOND) + 
			new Double(Math.random() * 1000).intValue()).getTime();
        obj.setShippedDate(shippedDate);
    }
    
}
