// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model.dod;

import br.com.rogrs.model.CustomerOrder;
import br.com.rogrs.model.OrderDetail;
import br.com.rogrs.model.Product;
import br.com.rogrs.model.dod.OrderDetailFactory;

privileged aspect OrderDetailFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link OrderDetail} with the given index.
     * 
     * @param index position of the OrderDetail
     * @return a new transient OrderDetail
     */
    public OrderDetail OrderDetailFactory.create(int index) {
        OrderDetail obj = new OrderDetail();
        setCustomerOrder(obj, index);
        setProduct(obj, index);
        setQuantity(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OrderDetailFactory.setCustomerOrder(OrderDetail obj, int index) {
        CustomerOrder customerOrder = null;
        obj.setCustomerOrder(customerOrder);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OrderDetailFactory.setProduct(OrderDetail obj, int index) {
        Product product = null;
        obj.setProduct(product);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void OrderDetailFactory.setQuantity(OrderDetail obj, int index) {
        Integer quantity = new Integer(index);
        obj.setQuantity(quantity);
    }
    
}
