// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model.dod;

import br.com.rogrs.model.Product;
import br.com.rogrs.model.dod.ProductFactory;

privileged aspect ProductFactory_Roo_JpaEntityFactory {
    
    /**
     * Creates a new {@link Product} with the given index.
     * 
     * @param index position of the Product
     * @return a new transient Product
     */
    public Product ProductFactory.create(int index) {
        Product obj = new Product();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void ProductFactory.setDescription(Product obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param obj
     * @param index
     */
    public void ProductFactory.setName(Product obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
}
