// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model;

import static org.assertj.core.api.Assertions.assertThat;

import br.com.rogrs.model.OrderDetail;
import br.com.rogrs.model.Product;
import br.com.rogrs.model.ProductTest;
import br.com.rogrs.model.dod.OrderDetailFactory;
import br.com.rogrs.model.dod.ProductFactory;
import java.util.Arrays;
import java.util.Collections;
import org.junit.Test;

privileged aspect ProductTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private OrderDetailFactory ProductTest.orderDetailFactory = new OrderDetailFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private ProductFactory ProductTest.productFactory = new ProductFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return OrderDetailFactory
     */
    public OrderDetailFactory ProductTest.getOrderDetailFactory() {
        return orderDetailFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param orderDetailFactory
     */
    public void ProductTest.setOrderDetailFactory(OrderDetailFactory orderDetailFactory) {
        this.orderDetailFactory = orderDetailFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return ProductFactory
     */
    public ProductFactory ProductTest.getProductFactory() {
        return productFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param productFactory
     */
    public void ProductTest.setProductFactory(ProductFactory productFactory) {
        this.productFactory = productFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @throws Exception
     */
    @Test
    public void ProductTest.addToOrderDetailsShouldAddTheOrderDetailToTheorderDetailsRelationship() throws Exception {
        // Setup
        Product product = getProductFactory().create(0);
        OrderDetail orderDetail1 = getOrderDetailFactory().create(0);
        OrderDetail orderDetail2 = getOrderDetailFactory().create(1);
        
        // Exercise
        product.addToOrderDetails(Arrays.asList(orderDetail1, orderDetail2));
        
        // Verify
        assertThat(product.getOrderDetails()).as("Check 'addToOrderDetails' adds the orderDetails to the relationship")
            .contains(orderDetail1).contains(orderDetail2);
        assertThat(product).as("Check 'addToOrderDetails' updates the OrderDetail relationship side")
            .isEqualTo(orderDetail1.getProduct()).isEqualTo(orderDetail2.getProduct());
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @throws Exception
     */
    @Test
    public void ProductTest.addToOrderDetailsShouldRemoveTheOrderDetailFromTheorderDetailsRelationship() throws Exception {
        // Setup
        Product product = getProductFactory().create(0);
        OrderDetail orderDetail1 = getOrderDetailFactory().create(0);
        OrderDetail orderDetail2 = getOrderDetailFactory().create(1);
        product.addToOrderDetails(Arrays.asList(orderDetail1, orderDetail2));
        
        // Exercise
        product.removeFromOrderDetails(Collections.singleton(orderDetail1));
        
        // Verify
        assertThat(orderDetail1.getProduct()).as("Check 'removeFromOrderDetails' updates the OrderDetail relationship side")
            .isNull();
        assertThat(product.getOrderDetails()).as("Check 'removeFromOrderDetails' removes a OrderDetail from the relationship")
            .doesNotContain(orderDetail1).contains(orderDetail2);
    }
    
}
