version: '2'
services:
    demo-app:
        image: demo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-postgresql:5432/demo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=demo-elasticsearch:9300
        ports:
            - 8080:8080
    demo-postgresql:
        extends:
            file: postgresql.yml
            service: demo-postgresql
    demo-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: demo-elasticsearch
