// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.web;

import br.com.rogrs.model.dod.CustomerOrderFactory;
import br.com.rogrs.service.api.CustomerOrderService;
import br.com.rogrs.web.CustomerOrdersCollectionJsonController;
import br.com.rogrs.web.CustomerOrdersCollectionJsonControllerIT;
import io.springlets.boot.test.autoconfigure.web.servlet.SpringletsWebMvcTest;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;

privileged aspect CustomerOrdersCollectionJsonControllerIT_Roo_JsonControllerIntegrationTest {
    
    declare @type: CustomerOrdersCollectionJsonControllerIT: @RunWith(SpringRunner.class);
    
    declare @type: CustomerOrdersCollectionJsonControllerIT: @SpringletsWebMvcTest(controllers = CustomerOrdersCollectionJsonController.class, secure = false);
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @Autowired
    private MockMvc CustomerOrdersCollectionJsonControllerIT.mvc;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    @MockBean
    private CustomerOrderService CustomerOrdersCollectionJsonControllerIT.customerOrderService;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private CustomerOrderFactory CustomerOrdersCollectionJsonControllerIT.factory = new CustomerOrderFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return MockMvc
     */
    public MockMvc CustomerOrdersCollectionJsonControllerIT.getMvc() {
        return mvc;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CustomerOrderService
     */
    public CustomerOrderService CustomerOrdersCollectionJsonControllerIT.getCustomerOrderService() {
        return customerOrderService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param customerOrderService
     */
    public void CustomerOrdersCollectionJsonControllerIT.setCustomerOrderService(CustomerOrderService customerOrderService) {
        this.customerOrderService = customerOrderService;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CustomerOrderFactory
     */
    public CustomerOrderFactory CustomerOrdersCollectionJsonControllerIT.getFactory() {
        return factory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param factory
     */
    public void CustomerOrdersCollectionJsonControllerIT.setFactory(CustomerOrderFactory factory) {
        this.factory = factory;
    }
    
    /**
     * Test method example. To be implemented by developer.
     * 
     */
    @Test
    public void CustomerOrdersCollectionJsonControllerIT.testMethodExample() {
        // Setup
        // Previous tasks
        
        // Exercise
        // Execute method to test
        
        // Verify
        // Check results with assertions
    }
    
}
