// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.com.rogrs.model;

import br.com.rogrs.model.CustomerFindByFirstNameAndLastName;
import io.springlets.format.EntityFormat;

privileged aspect CustomerFindByFirstNameAndLastName_Roo_DTO {
    
    declare @type: CustomerFindByFirstNameAndLastName: @EntityFormat;
    
}
